### DISCUSSION TITLE
lamp-gateway-server模块启动报错

### DISCUSSION THREAD

**Discussion by pengju-123** [zuihou/zuihou-admin-cloud#102] [01.常见问题]
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/config/annotation/WebMvcConfigurer.class] cannot be opened because it does not exist

应该是由于版本冲突导致的

**Comment by zuihou** [comment]
nacos 中lamp-gateway-server.yml 不正确


```
lamp:
  log:
    enabled: false
  webmvc:
    enabled: false

spring:
  autoconfigure:
    exclude: io.seata.integration.http.HttpAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
```
