### DISCUSSION TITLE
can not get cluster name in registry config

### DISCUSSION THREAD

**Discussion by Angle-bo** [zuihou/zuihou-admin-cloud#116] [01.常见问题]
分布式事务seata，一直警告，服务未注册。

**Comment by zuihou** [comment]
1. mysql.yml  配置加上：  `dataId: seataServer.properties`

```
# 分布式事务相关
seata:
  enabled: ${lamp.database.isSeata}
  enableAutoDataSourceProxy: true
  tx-service-group: lamp_cloud_seata_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: ${lamp.nacos.ip}:${lamp.nacos.port}
      username: ${lamp.nacos.username}
      password: ${lamp.nacos.password}
      namespace: ${lamp.seata.namespace}
  config:
    type: nacos
    nacos:
      server-addr: ${lamp.nacos.ip}:${lamp.nacos.port}
      username: ${lamp.nacos.username}
      password: ${lamp.nacos.password}
      namespace: ${lamp.seata.namespace}

## 之前导出的配置少了这个
      dataId: seataServer.properties
  service:
    grouplist:
      default: ${lamp.seata.ip:}:${lamp.seata.port:}
    vgroup-mapping:
      lamp_cloud_seata_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false
```
2. seata的配置，全部导入： seataServer.properties
