### DISCUSSION TITLE
某个服务需要多数据源配置需要特殊的配置吗 还是正常的按照多数据源配？

### DISCUSSION THREAD

**Discussion by zqb666** [zuihou/zuihou-admin-cloud#262] [02.提问]
某个服务需要多数据源配置需要特殊的配置吗 还是正常的按照多数据源配？
之前你说过 某个服务在对应服务的yml文件里配了数据库连接就会走自己的数据库配置不会走共用的mysql.yml
或者能贴个 多数据源的示例配置吗 我代码里通过@DS注解去 走

**Comment by zuihou** [comment]
lamp-cloud-pro-datasource-column 项目默认 所有服务都集成了多数据源，以实现不同的租户访问不同的数据库。

某个服务在对应服务的yml文件里配了跟mysql.yml中相同的配置，就会走自己的这部分配置，不会走共用的mysql.yml。 （一定是mysql.yml中已经配置的属性，在对应服务中去覆盖）

配置代码在 lamp-cloud-pro-datasource-column 项目的 database.yml 中。

**Reply by zqb666** [reply]
lamp-cloud-pro-datasource-column 这个是收费的吧？看不到

**Reply by zuihou** [reply]
开源版 没有配置多数据源，需要自行查阅资料进行集成。

**Reply by zqb666** [reply]
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/6092525/229117904-6dfbfd5c-7245-42c8-956d-0fa79131d773.png">

 我用了lamp-cloud-pro-datasource-column 项目的 database.yml 配置 为什么启动报这个错
这是我的完整配置 ip密码为了隐私做了特殊处理  能帮我看看哪里有问题吗 大佬
```
### 
server:
  port: 8774
lamp:
  swagger:
    title: eicu服务
    base-package: top.tangyh.lamp
  druid-oracle: &druid-oracle
    validation-query: SELECT 'x' FROM DUAL
  druid-mysql: &druid-mysql
    validation-query: SELECT 'x'
  # druid-sqlserver: &druid-sqlserver
  #   validation-query: SELECT 'x'
  oracle: &db-oracle
    username: 'yxkj'
    password: 'yxkj'
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@129.10.0.183:1521/CDR
  mysql: &db-mysql
    username: 'root'
    password: 'xxx'
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip1:3306/yx_medical_cloud?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
  ck: &db-ck
    username: 'default'
    password: 'xxx'
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://ip2:8123/yx_icu
  ck2: &db-ck2
    username: 'default'
    password: 'xxx'   
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://ip3:8123/yixuan
  database: # 字段介绍参考 DatabaseProperties
    # COLUMN模式中隔离 租户 的列名  oracle数据库initDatabasePrefix不能超过11个字符
    initDatabasePrefix:
      - lamp_base
    tenantIdColumn: tenant_code
    multiTenantType: COLUMN
    # 是否不允许写入数据  WriteInterceptor
    isNotWrite: false
    # 是否启用数据权限
    isDataScope: true
    # 是否启用  sql性能规范插件
    isBlockAttack: false
    # 是否启用  sql性能规范插件
    isIllegalSql: false
    # 是否启用分布式事务
    isSeata: false
    # 生产环境请设置p6spy = false
    p6spy: true
    # 单页分页条数限制
    maxLimit: -1
    # 溢出总页数后是否进行处理
    overflow: true
    # 生成 countSql 优化掉 join, 现在只支持 left join
    optimizeJoin: true
    # id生成策略
    id-type: CACHE
    hutoolId:
      workerId: 0
      dataCenterId: 0
    cache-id:
      time-bits: 31
      worker-bits: 22
      seq-bits: 10
      epochStr: '2020-09-15'
      boost-power: 3
      padding-factor: 50

# mysql 通用配置
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    dynamic:
      enabled: true
      # 从这里开始(dynamic)，中间的这段配置用于 lamp.database.multiTenantType == DATASOURCE 时
      p6spy: ${lamp.database.p6spy:false}
      seata: ${lamp.database.isSeata:false}
      primary: "0"
      datasource:
        "0":
          <<: *db-mysql
          # <<: *db-sqlserver
          # <<: *db-ck
          # <<: *db-ck2
          # <<: *db-oracle
      druid:
        <<: *druid-mysql      
        # <<: *db-ck
        # <<: *db-ck2
        # <<: *druid-oracle  
        initialSize: 10
        minIdle: 10
        maxActive: 200
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
        filters: stat,wall
        wall:
          enabled: true
          strictSyntaxCheck: false
          comment-allow: true
          multiStatementAllow: true
          noneBaseStatementAllow: true

    # 从这里结束(dynamic)，中间的这段配置用于 lamp.database.multiTenantType == DATASOURCE 时
    druid:
      enable: true
      # 以下的2段配置，同时适用于所有模式
      web-stat-filter:  # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:  #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
        enabled: true
        url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
        reset-enable: true    #允许清空统计数据
        login-username: ''
        login-password: ''
        # 允许访问IP
        allow: ''

mybatis-plus:
  mapper-locations:
    - classpath*:mapper_**/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: top.tangyh.lamp.*.entity;top.tangyh.basic.database.mybatis.typehandler
  typeEnumsPackage: top.tangyh.lamp.*.enumeration
  global-config:
    db-config:
      id-type: INPUT
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      where-strategy: NOT_EMPTY
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    default-enum-type-handler: top.tangyh.basic.database.mybatis.handlers.MybatisEnumTypeHandler

# 分布式事务相关
seata:
  enabled: ${lamp.database.isSeata}
  enableAutoDataSourceProxy: ${lamp.database.isSeata}
  tx-service-group: lamp_cloud_seata_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: ${lamp.nacos.ip}:${lamp.nacos.port}
      username: ${lamp.nacos.username}
      password: ${lamp.nacos.password}
      namespace: ${lamp.seata.namespace}
  config:
    type: nacos
    nacos:
      server-addr: ${lamp.nacos.ip}:${lamp.nacos.port}
      username: ${lamp.nacos.username}
      password: ${lamp.nacos.password}
      namespace: ${lamp.seata.namespace}
      dataId: seataServer.properties
  service:
    grouplist:
      default: ${lamp.seata.ip:}:${lamp.seata.port:}
    vgroup-mapping:
      lamp_cloud_seata_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false
```
