### DISCUSSION TITLE
gateway在启动时卡住

### DISCUSSION THREAD

**Discussion by reamZMX** [zuihou/zuihou-admin-cloud#357] [02.提问] [answered]
# 版本信息 （必填）：
后端使用的是lamp-cloud-datasource-column
前端使用的是lamp-web-pro
JDK 版本(必填) : 8
源码版本(必填)：4.21.2
MySQL(必填)： 8.0.35
Nacos(必填)：2.3.1

# 问题描述：
我从仓库拉取的最新的代码，没有做任何更改（除了更改config-dev文件的nacos地址等）
当我运行base，system等模块是能正常启动
然而当我启动gateway模块时 报错如下：
# 报错截图
![image](https://github.com/user-attachments/assets/05228be9-2278-4655-840d-d3d527d48ff2)
这个错误当我放出了lamp-gateway-server的pom中的webmvc时就没有了
![image](https://github.com/user-attachments/assets/e9ac4d82-91c0-4a95-92c1-ff44aca7218d)
然后会卡在这里：
![image](https://github.com/user-attachments/assets/c6ac8cc8-9a89-413d-af94-b71778f869a4)
其他项目可正常启动
![image](https://github.com/user-attachments/assets/ac2dab64-2334-447b-9480-9d529e762fe5)

# 重现步骤
1. 拉取代码修改config-dev文件
2. 运行gateway的application
3. 修改lamp-gateway-server的pom（不改会报错），重新maven加载一下
4. 卡住不启动

**Comment by reamZMX** [comment]
nacos配置是：
```
lamp:
  log:
    enabled: false
  webmvc:
    undertow: false
    header: false
  authentication:
    # jwt 签名，长度至少32位。 建议每个公司都修改一下这个字符串。 lamp-oauth-server.yml 和 lamp-gateway-server.yml 中这个配置必须一样
    jwtSignKey: 'lamp-cloud_is_a_fantastic_project'
  database:
    initDatabasePrefix:
      - lamp_base
  ignore:
    # 是否启用网关的 uri权限鉴权 (设置为false，则后台不校验访问权限)
    authEnabled: true
    # 前端校验按钮 是否区分大小写
    caseSensitive: false
    anyone:       # 请求中 需要携带Tenant 且 需要携带Token(需要登录)，但不需要验证uri权限
      ALL:
        - /**/anyone/**
    anyUser:      # 请求中 需要携带Tenant，但 不需要携带Token(不需要登录) 和 不需要验证uri权限
      ALL:
        - /**/anyUser/**
    anyTenant:    # 请求中 不需要携带Tenant 且 不需要携带Token(不需要登录) 和 不需要验证uri权限
      ALL:
        - /**/anyTenant/**
spring:
  autoconfigure:
    exclude: io.seata.integration.http.HttpAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      x-forwarded:
        prefixEnabled: false
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # 新建服务配置复制到中间
        - id: order
          uri: lb://lamp-order-server
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: info
          uri: lb://lamp-info-server
          predicates:
            - Path=/info/**
          filters:
            - StripPrefix=1
        # 新建服务配置复制到中间
        - id: oauth
          uri: lb://lamp-oauth-server
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
        - id: system
          uri: lb://lamp-system-server
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: base
          uri: lb://lamp-base-server
          predicates:
            - Path=/base/**
          filters:
            - StripPrefix=1
        # websocket
        - id: wsMsg
          uri: lb:ws://lamp-base-server
          predicates:
            - Path=/wsMsg/**
          filters:
            - StripPrefix=1
        - id: generator
          uri: lb://lamp-generator-server
          predicates:
            - Path=/generator/**
          filters:
            - StripPrefix=1
        - id: dd
          uri: lb://lamp-dd-server
          predicates:
            - Path=/dd/**
          filters:
            - StripPrefix=1            

server:
  port: 18760
  servlet:
    context-path: /api

```
我看了相关配置是正确的
