### DISCUSSION TITLE
lamp-datasource-max后台服务jar包在服务器上启动失败，本地idea可以正常运行

### DISCUSSION THREAD

**Discussion by cdragon945cd** [zuihou/zuihou-admin-cloud#385] [02.提问] [answered]
测试部署到服务器时，后端项目jar包启动失败
请帮忙指点一下是哪里出现问题了

项目版本 lamp-datasource-max 5.1.0

服务器环境如下
服务器系统 centos 8.2.2004
jdk版本 openjdk 17.0.1 2021-10-19LTS
nacos版本2.4.0.1
seata版本2.0.0
redis版本5.0.3
rabbitmq版本4.1.0

配置文件如下
![config-
![lamp-oauth-server-bootstrap yml](https://github.com/user-attachments/assets/b377fbfb-05ff-474b-843e-96b25556fee0)
prod properties](https://github.com/user-attachments/assets/1db9c79d-034c-49c2-9af6-e37cf57a10d1)
![image](https://github.com/user-attachments/assets/2206b2df-7195-41a9-b58a-785ff5eeaa14)
![image](https://github.com/user-attachments/assets/b2a9bba8-a9a2-4af1-987c-d546e3e77271)
![image](https://github.com/user-attachments/assets/57d0afa1-7d18-488f-8c05-1faa2c154eeb)
![image](https://github.com/user-attachments/assets/7723b0a6-7728-440c-8450-f89dca6bb010)
![image](https://github.com/user-attachments/assets/a0e0236e-8b5d-48d1-93c9-07ee75433d23)

报错信息如下
![lamp-oauth-server-error](https://github.com/user-attachments/assets/0d54a52c-baa7-4e51-84ce-bcc3c9408cd4)
![lamp-base-server error](https://github.com/user-attachments/assets/12f571bf-2174-4035-a62f-96f5cba10745)

**Comment by cdragon945cd** [comment]
seata和nacos在两台不同的服务器上，都有固定ip
seata的配置
![image](https://github.com/user-attachments/assets/fcd31b2a-e354-479f-823c-1b93a9afe8f2)
![image](https://github.com/user-attachments/assets/97dcd983-7c5e-4218-9898-b4bb7a1882c8)

**Comment by zuihou** [comment]
看一下 .mysql.yml 里面的配置： 

```

# 分布式事务相关
seata:
  enabled: ${lamp.database.isSeata}
  enableAutoDataSourceProxy: ${lamp.database.isSeata}
  tx-service-group: lamp_cloud_seata_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: ${lamp.nacos.ip}:${lamp.nacos.port}
      username: ${lamp.nacos.username}
      password: ${lamp.nacos.password}
      namespace: ${lamp.seata.namespace}
      group: 'SEATA_GROUP'
  config:
    type: nacos
    nacos:
      server-addr: ${lamp.nacos.ip}:${lamp.nacos.port}
      username: ${lamp.nacos.username}
      password: ${lamp.nacos.password}
      namespace: ${lamp.seata.namespace}
      group: 'SEATA_GROUP'
      dataId: seataServer.properties
  service:
    grouplist:
      default: ${lamp.seata.ip:}:${lamp.seata.port:}
    vgroupMapping:
      lamp_cloud_seata_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false
```

**Reply by cdragon945cd** [reply]
nacos中mysql.yml的seata部分配置跟您发的一致
![image](https://github.com/user-attachments/assets/b38ebee3-2859-45dc-b74e-c931553d5241)

mysql.yml的全部配置信息如下（数据库连接的用户名密码和ip可以忽略）
```
lamp:
  druid-mysql: &druid-mysql
    validation-query: SELECT 'x'
  mysql: &db-mysql
    username: '123456'
    password: '123456'
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lamp_ds_c_defaults?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
  database: # 字段介绍参考 DatabaseProperties
    # COLUMN模式中隔离 租户 的列名  oracle数据库initDatabasePrefix不能超过11个字符
    initDatabasePrefix:
      - lamp_base
    tenantIdColumn: 'created_org_id'
    multiTenantType: DATASOURCE_COLUMN
    # 是否启用数据权限
    isDataScope: true
    # 是否启用  sql性能规范插件
    isBlockAttack: false
    # 是否启用  sql性能规范插件
    isIllegalSql: false
    # 是否启用分布式事务
    isSeata: false
    # 生产环境请设置p6spy = false
    p6spy: true
    # 单页分页条数限制
    maxLimit: -1
    # 溢出总页数后是否进行处理
    overflow: true
    # 生成 countSql 优化掉 join, 现在只支持 left join
    optimizeJoin: true
    # id生成策略  # HU_TOOL  DEFAULT
    id-type: CACHE
    hutoolId:
      workerId: 0
      dataCenterId: 0    
    cache-id:
      time-bits: 31
      worker-bits: 22
      seq-bits: 10
      epochStr: '2020-09-15'
      boost-power: 3
      padding-factor: 50

# mysql 通用配置
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    dynamic:
      enabled: true
      # 从这里开始(dynamic)，中间的这段配置用于 lamp.database.multiTenantType == DATASOURCE 时
      p6spy: ${lamp.database.p6spy:false}
      seata: ${lamp.database.isSeata:false}
      primary: "0"
      datasource:
        "0":
          <<: *db-mysql
      druid:
        <<: *druid-mysql
        initialSize: 10
        minIdle: 10
        maxActive: 200
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        test-on-borrow: true
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
        filters: stat,wall
        wall:
          enabled: true
          strictSyntaxCheck: false
          comment-allow: true
          multiStatementAllow: true
          noneBaseStatementAllow: true

    # 从这里结束(dynamic)，中间的这段配置用于 lamp.database.multiTenantType == DATASOURCE 时
    druid:
      enable: true
      # 以下的2段配置，同时适用于所有模式
      web-stat-filter:  # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:  #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
        enabled: true
        url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
        reset-enable: true    #允许清空统计数据
        login-username: ''
        login-password: ''
        # 允许访问IP
        allow: ''

mybatis-plus:
  mapper-locations:
    - classpath*:mapper_**/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: top.tangyh.lamp.*.entity;top.tangyh.basic.database.mybatis.typehandler
  typeEnumsPackage: top.tangyh.lamp.*.enumeration
  global-config:
    db-config:
      id-type: INPUT
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      where-strategy: NOT_EMPTY
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    default-enum-type-handler: top.tangyh.basic.database.mybatis.handlers.MybatisEnumTypeHandler

# 分布式事务相关
seata:
  enabled: ${lamp.database.isSeata}
  enableAutoDataSourceProxy: ${lamp.database.isSeata}
  tx-service-group: lamp_cloud_seata_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: ${lamp.nacos.ip}:${lamp.nacos.port}
      username: ${lamp.nacos.username}
      password: ${lamp.nacos.password}
      namespace: ${lamp.seata.namespace}
      group: 'SEATA_GROUP'
  config:
    type: nacos
    nacos:
      server-addr: ${lamp.nacos.ip}:${lamp.nacos.port}
      username: ${lamp.nacos.username}
      password: ${lamp.nacos.password}
      namespace: ${lamp.seata.namespace}
      group: 'SEATA_GROUP'
      dataId: seataServer.properties
  service:
    grouplist:
      default: ${lamp.seata.ip:}:${lamp.seata.port:}
    vgroupMapping:
      lamp_cloud_seata_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false
```
