### DISCUSSION TITLE
系统常用的密码在那里修改？

### DISCUSSION THREAD

**Discussion by zuihou** [zuihou/zuihou-admin-cloud#67] [02.提问]
系统中涉及的密码在什么地方修改？

**Comment by zuihou** [comment]
# lamp-cloud系统
1. druid监控系统的登录密码位于 mysql.yml
```
spring:
  datasource:
    druid:
      stat-view-servlet:  #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
        enabled: true
        url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
        reset-enable: true   
        login-username: lamp
        login-password: lamp
```
2. 项目连接 mysql 的密码 位于 mysql.yml
```
lamp:
  mysql:
    username: 'root'
    password: 'root'
```
3. 项目连接 redis 的密码 位于 redis.yml
```
lamp:
  redis:
    password: 'xxxx'   # 若redis无密码，请设置为 '' 字符串
```
4. 项目连接 rabbitmq 的密码 位于 rabbitmq.yml
```
lamp:
  rabbitmq:
    ip: 127.0.0.1
    port: 5672
    username: 'lamp'
    password: 'lamp'    # 不推荐使用默认账号和密码 guest
```
5. 登录 lamp-web 的账号密码位于 c_user 表
6. 项目启动时，连接nacos的密码位于bootstrap.yml
```
lamp:
  nacos:
    username: ${NACOS_USERNAME:@nacos.username@}
    password: ${NACOS_PASSWORD:@nacos.password@}
```

**Comment by zuihou** [comment]
# lamp-boot
1. druid监控系统的登录密码位于 application.yml
```
spring:
  datasource:
    druid:
      stat-view-servlet:  #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
        enabled: true
        url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
        reset-enable: true   
        login-username: lamp
        login-password: lamp
```
2. 项目连接 mysql 的密码 位于 mysql.yml
```
lamp:
  mysql:
    username: 'root'
    password: 'root'
```
3. 项目连接 redis 的密码 位于 application.yml
```
lamp:
  redis:
    password: 'xxxx'   # 若redis无密码，请设置为 '' 字符串
```
4. 项目连接 rabbitmq 的密码 位于 application.yml
```
lamp:
  rabbitmq:
    ip: 127.0.0.1
    port: 5672
    username: 'lamp'
    password: 'lamp'    # 不推荐使用默认账号和密码 guest
```
5. 登录 lamp-web 的账号密码位于 c_user 表
