### DISCUSSION TITLE
新建项目或者新建模块后， swagger文档中无法看到自己的文档

### DISCUSSION THREAD

**Discussion by zuihou** [zuihou/zuihou-admin-cloud#69] [01.常见问题]
新建项目或者新建模块后， swagger文档中无法看到自己的文档

**Comment by zuihou** [comment]
1. 在yml中配置新建的controller类所在包名
```
lamp:
  swagger:
    docket:
      msg:  # 消息服务，这里可以任意命名，别重复即可
        title: 消息服务  
        base-package: com.tangyh.lamp.msg.controller;com.tangyh.lamp.sms.controller  # 支持; 分割多个包
```
2. 在server模块的pom中加入controller模块的依赖
```
        <dependency>
            <groupId>com.tangyh.lamp</groupId>
            <artifactId>lamp-xxxx-controller</artifactId>
            <version>${lamp-project.version}</version>
        </dependency>
```


正常情况，按此配置，启动项目后即可访问文档
