### ISSUE TITLE
多个数据库链接及关联查询问题

### ISSUE THREAD

**Issue by shangguanbaojun** [zuihou/zuihou-admin-cloud#361]
5.X资助版column模式下。
### 1、数据库连接
新建一个服务后，这个服务能不能单独连接一个库，其他的模块还是连接默认的lamp_column库，新建的服务连接其他的库。如果能实现，怎么实现？

**Comment by zuihou** [comment]
1. 默认都是column库，  可以在各自服务配置文件中修改配置链接其他库. 相当于就是各自服务的配置文件优先级大于mysql.yml里面的配置
```
# mysql 通用配置
spring:
  datasource:
    druid:
      enable: true
      db-type: mysql   
      validation-query: SELECT 'x'  
      filters: stat,wall
      username: 'root'
      password: 'root' 
      driverClassName: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://127.0.0.1:3306/lamp_column?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
```
3. 多表操作请看 mybatis-plus 和 mybatis 相关资料，lamp只是集成了各个组件，没有发明新的持久层组件。 mybatis-plus 和 mybatis 能做的操作，在本项目中仅支持。
